### ISSUE TITLE
Update to voice-sdk

### ISSUE THREAD

**Issue by bosticka** [twilio/rtc-diagnostics-react-app#61]
**What is the feature that you would like to see in the SDK? Please describe.**
This test library is using a deprecated sdk, twilio-client.  Can you update the test to @twilio/voice-sdk version 2.01?

**Is your feature request related to a problem? Please describe.**
Older no longer maintained library is used.

**Describe alternatives you've considered**
Use @twilio/voice-sdk

**Additional context**

**Comment by charliesantos** [comment]
@bosticka thanks for the report! We have an internal ticket for this effort. Please watch this space for future updates.

**Comment by olipyskoty** [comment]
Hi @bosticka, this app has been updated to use `@twilio/voice-sdk`, and no longer uses the `twilio-client` library. Please let us know if you have any other questions. Thank you!
